### ISSUE TITLE
/songdownload

### ISSUE THREAD

**Issue by Vadokk** [Navoei/CustomDiscs#22] opened 2022-12-31 22:21 UTC
Cool plugin!  But still it would be cool if players could upload music themselves. I know this has been suggested before, but how is the progress?

**Comment by BaxAndrei** [comment] 2023-02-15 08:42
BUMP!

**Comment by Navoei** [comment] 2023-03-31 20:43
This is currently being worked on :)

**Comment by Navoei** [comment] 2023-03-31 20:45
when using the create command, you can specify a url like this:
`/cd create "Disc Name" directory/songfile.mp3`
Keep in mind that the directory must be a folder inside the musicdata folder.

**Comment by Navoei** [comment] 2023-04-01 01:07
This is a duplicate of #1

**Closed** 2023-04-01 01:07 UTC
